
disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - attributes
  - closure_spacing
  - colon
  - operator_usage_whitespace
  - fatal_error_message
  - trailing_closure
  - empty_count
  - function_default_parameter_at_end
  - prefer_self_in_static_references
  - identifier_name # 사용 전 Rule 확인 필요

analyzer_rules:
  - unused_declaration

line_length:
  warning: 120
  error: 200

type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 40
    error: 50

identifier_name:
  min_length: 3

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 200
  error: 400

indentation:
  indentation_width: 2
  include_comments: true

colon:
  flexible_right_spacing: false
  apply_to_dictionaries: true

operator_usage_whitespace:
  severity: warning

type_name:
  validates_start_with_lowercase: warning

control_statement:
  severity: warning
  if_else: false

void_return:
  severity: warning